package com.lcdt.items.model;

public class CustomValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.vid
     *
     * @mbg.generated
     */
    private Long vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.item_id
     *
     * @mbg.generated
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.sub_item_id
     *
     * @mbg.generated
     */
    private Long subItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.property_field
     *
     * @mbg.generated
     */
    private String propertyField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.property_value
     *
     * @mbg.generated
     */
    private String propertyValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.property_name
     *
     * @mbg.generated
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.property_type
     *
     * @mbg.generated
     */
    private Short propertyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_custom_value.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.vid
     *
     * @return the value of t_custom_value.vid
     *
     * @mbg.generated
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.vid
     *
     * @param vid the value for t_custom_value.vid
     *
     * @mbg.generated
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.item_id
     *
     * @return the value of t_custom_value.item_id
     *
     * @mbg.generated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.item_id
     *
     * @param itemId the value for t_custom_value.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.sub_item_id
     *
     * @return the value of t_custom_value.sub_item_id
     *
     * @mbg.generated
     */
    public Long getSubItemId() {
        return subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.sub_item_id
     *
     * @param subItemId the value for t_custom_value.sub_item_id
     *
     * @mbg.generated
     */
    public void setSubItemId(Long subItemId) {
        this.subItemId = subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.property_field
     *
     * @return the value of t_custom_value.property_field
     *
     * @mbg.generated
     */
    public String getPropertyField() {
        return propertyField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.property_field
     *
     * @param propertyField the value for t_custom_value.property_field
     *
     * @mbg.generated
     */
    public void setPropertyField(String propertyField) {
        this.propertyField = propertyField == null ? null : propertyField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.property_value
     *
     * @return the value of t_custom_value.property_value
     *
     * @mbg.generated
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.property_value
     *
     * @param propertyValue the value for t_custom_value.property_value
     *
     * @mbg.generated
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.property_name
     *
     * @return the value of t_custom_value.property_name
     *
     * @mbg.generated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.property_name
     *
     * @param propertyName the value for t_custom_value.property_name
     *
     * @mbg.generated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.property_type
     *
     * @return the value of t_custom_value.property_type
     *
     * @mbg.generated
     */
    public Short getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.property_type
     *
     * @param propertyType the value for t_custom_value.property_type
     *
     * @mbg.generated
     */
    public void setPropertyType(Short propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_custom_value.company_id
     *
     * @return the value of t_custom_value.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_custom_value.company_id
     *
     * @param companyId the value for t_custom_value.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}