package com.lcdt.items.model;

import java.util.Date;

/**
 * 商品规格名称表
 */
public class ItemSpecKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_spec_key.spk_id
     *
     * @mbg.generated
     */
    private Long spkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_spec_key.sp_name
     *
     * @mbg.generated
     */
    private String spName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_item_spec_key.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    private Long createId;

    private String createName;

    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_spec_key.spk_id
     *
     * @return the value of t_item_spec_key.spk_id
     *
     * @mbg.generated
     */
    public Long getSpkId() {
        return spkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_spec_key.spk_id
     *
     * @param spkId the value for t_item_spec_key.spk_id
     *
     * @mbg.generated
     */
    public void setSpkId(Long spkId) {
        this.spkId = spkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_spec_key.sp_name
     *
     * @return the value of t_item_spec_key.sp_name
     *
     * @mbg.generated
     */
    public String getSpName() {
        return spName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_spec_key.sp_name
     *
     * @param spName the value for t_item_spec_key.sp_name
     *
     * @mbg.generated
     */
    public void setSpName(String spName) {
        this.spName = spName == null ? null : spName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_item_spec_key.company_id
     *
     * @return the value of t_item_spec_key.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_item_spec_key.company_id
     *
     * @param companyId the value for t_item_spec_key.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCreateId() {
        return createId;
    }

    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}