package com.lcdt.items.model;

/**
 * 子商品
 */
public class SubItemsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.sub_item_id
     *
     * @mbg.generated
     */
    private Long subItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.item_id
     *
     * @mbg.generated
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.bar_code
     *
     * @mbg.generated
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.purchase_price
     *
     * @mbg.generated
     */
    private Float purchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.wholesale_price
     *
     * @mbg.generated
     */
    private Float wholesalePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.retail_price
     *
     * @mbg.generated
     */
    private Float retailPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.spec_comb
     *
     * @mbg.generated
     */
    private String specComb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sub_items_info.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.sub_item_id
     *
     * @return the value of t_sub_items_info.sub_item_id
     *
     * @mbg.generated
     */
    public Long getSubItemId() {
        return subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.sub_item_id
     *
     * @param subItemId the value for t_sub_items_info.sub_item_id
     *
     * @mbg.generated
     */
    public void setSubItemId(Long subItemId) {
        this.subItemId = subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.item_id
     *
     * @return the value of t_sub_items_info.item_id
     *
     * @mbg.generated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.item_id
     *
     * @param itemId the value for t_sub_items_info.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.code
     *
     * @return the value of t_sub_items_info.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.code
     *
     * @param code the value for t_sub_items_info.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.bar_code
     *
     * @return the value of t_sub_items_info.bar_code
     *
     * @mbg.generated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.bar_code
     *
     * @param barCode the value for t_sub_items_info.bar_code
     *
     * @mbg.generated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.purchase_price
     *
     * @return the value of t_sub_items_info.purchase_price
     *
     * @mbg.generated
     */
    public Float getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.purchase_price
     *
     * @param purchasePrice the value for t_sub_items_info.purchase_price
     *
     * @mbg.generated
     */
    public void setPurchasePrice(Float purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.wholesale_price
     *
     * @return the value of t_sub_items_info.wholesale_price
     *
     * @mbg.generated
     */
    public Float getWholesalePrice() {
        return wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.wholesale_price
     *
     * @param wholesalePrice the value for t_sub_items_info.wholesale_price
     *
     * @mbg.generated
     */
    public void setWholesalePrice(Float wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.retail_price
     *
     * @return the value of t_sub_items_info.retail_price
     *
     * @mbg.generated
     */
    public Float getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.retail_price
     *
     * @param retailPrice the value for t_sub_items_info.retail_price
     *
     * @mbg.generated
     */
    public void setRetailPrice(Float retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.spec_comb
     *
     * @return the value of t_sub_items_info.spec_comb
     *
     * @mbg.generated
     */
    public String getSpecComb() {
        return specComb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.spec_comb
     *
     * @param specComb the value for t_sub_items_info.spec_comb
     *
     * @mbg.generated
     */
    public void setSpecComb(String specComb) {
        this.specComb = specComb == null ? null : specComb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sub_items_info.company_id
     *
     * @return the value of t_sub_items_info.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sub_items_info.company_id
     *
     * @param companyId the value for t_sub_items_info.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}