package com.lcdt.wms.permission.dao;

import com.lcdt.wms.permission.model.WmsPermission;

import java.util.List;

public interface WmsPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_permission
     *
     * @mbg.generated
     */
    int insert(WmsPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_permission
     *
     * @mbg.generated
     */
    WmsPermission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_permission
     *
     * @mbg.generated
     */
    List<WmsPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WmsPermission record);
}