package com.lcdt.wms.permission.dao;

import com.lcdt.wms.permission.model.WmsUserRole;

import java.util.List;

public interface WmsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_user_role
     *
     * @mbg.generated
     */
    int insert(WmsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_user_role
     *
     * @mbg.generated
     */
    WmsUserRole selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_user_role
     *
     * @mbg.generated
     */
    List<WmsUserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WmsUserRole record);

    List<WmsUserRole> selctRoleByUser(Integer userId, Long companyId);

}