package com.lcdt.customer.dao;

import com.lcdt.customer.model.CustomerInviteLog;

import java.util.List;

public interface CustomerInviteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_invite_log
     *
     * @mbg.generated Tue Nov 28 09:21:08 CST 2017
     */
    int deleteByPrimaryKey(Long inviteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_invite_log
     *
     * @mbg.generated Tue Nov 28 09:21:08 CST 2017
     */
    int insert(CustomerInviteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_invite_log
     *
     * @mbg.generated Tue Nov 28 09:21:08 CST 2017
     */
    CustomerInviteLog selectByPrimaryKey(Long inviteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_invite_log
     *
     * @mbg.generated Tue Nov 28 09:21:08 CST 2017
     */
    List<CustomerInviteLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_invite_log
     *
     * @mbg.generated Tue Nov 28 09:21:08 CST 2017
     */
    int updateByPrimaryKey(CustomerInviteLog record);
}