package com.lcdt.customer.dao;

import com.lcdt.customer.model.CustomerContact;

import java.util.List;

public interface CustomerContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Fri Nov 24 10:56:38 CST 2017
     */
    int deleteByPrimaryKey(Long contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Fri Nov 24 10:56:38 CST 2017
     */
    int insert(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Fri Nov 24 10:56:38 CST 2017
     */
    CustomerContact selectByPrimaryKey(Long contactId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Fri Nov 24 10:56:38 CST 2017
     */
    List<CustomerContact> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Fri Nov 24 10:56:38 CST 2017
     */
    int updateByPrimaryKey(CustomerContact record);
}