package com.lcdt.clms.permission.dao;

import com.lcdt.clms.permission.model.RoleUserRelation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleUserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_relation
     *
     * @mbg.generated
     */
    int insert(RoleUserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_relation
     *
     * @mbg.generated
     */
    RoleUserRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_relation
     *
     * @mbg.generated
     */
    List<RoleUserRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleUserRelation record);


    List<RoleUserRelation> selectByUserAndCompany(@Param("userId") Long userId, @Param("companyId") Long companyId);

    List<RoleUserRelation> selectByRoleId(Long roleId);

}