package com.lcdt.wms.permission.dao;

import com.lcdt.wms.permission.model.WmsRole;

import java.util.List;

public interface WmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_role
     *
     * @mbg.generated
     */
    int insert(WmsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_role
     *
     * @mbg.generated
     */
    WmsRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_role
     *
     * @mbg.generated
     */
    List<WmsRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_up_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WmsRole record);
}