package com.lcdt.contract.dao;


import java.util.List;

import com.lcdt.contract.model.OrderProduct;

public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbggenerated
     */
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbggenerated
     */
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderProduct record);

    int deleteByCompanyId(Long companyId);
    
    
    /**
     *删除订单下的商品
     */
    int deleteByOrderId(Long orderId);
    
    /**
     *获取某订单下的商品
     */
    List<OrderProduct> getOrderProductByOrderId(Long orderId);


    /**
     * 根据orderIds数组获取产品信息
     * @param orderIds
     * @return
     */
    List<OrderProduct> selectProductByOrderIds(String[] orderIds);
    
    
    /**
     * 统计一篮子订单下订单商品的数量
     * @param orderIds
     * @return
     */
    Integer getProductCountByOrderIds(List<Long> orderIds);
    
    
    
    
}