package com.lcdt.goods.dao;

import com.lcdt.goods.model.GoodsSku;

import java.util.List;

public interface GoodsSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodsSkuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sku
     *
     * @mbg.generated
     */
    int insert(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sku
     *
     * @mbg.generated
     */
    GoodsSku selectByPrimaryKey(Long goodsSkuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sku
     *
     * @mbg.generated
     */
    List<GoodsSku> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsSku record);
}