package com.lcdt.goods.dao;

import com.lcdt.goods.model.GoodsProperty;

import java.util.List;
import java.util.Map;

public interface GoodsPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodsPropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property
     *
     * @mbg.generated
     */
    int insert(GoodsProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property
     *
     * @mbg.generated
     */
    GoodsProperty selectByPrimaryKey(Long goodsPropertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property
     *
     * @mbg.generated
     */
    List<GoodsProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsProperty record);


    List<GoodsProperty> selectByCondition(Map map);


}