package com.lcdt.goods.dao;

import com.lcdt.goods.model.GoodsProperty;
import com.lcdt.goods.model.GoodsPropertyValue;

import java.util.List;
import java.util.Map;

public interface GoodsPropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long propertyValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property_value
     *
     * @mbg.generated
     */
    int insert(GoodsPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property_value
     *
     * @mbg.generated
     */
    GoodsPropertyValue selectByPrimaryKey(Long propertyValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property_value
     *
     * @mbg.generated
     */
    List<GoodsPropertyValue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_property_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsPropertyValue record);

    List<GoodsPropertyValue> selectByCondition(Map map);
}