package com.lcdt.contract.model;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

import io.swagger.annotations.ApiModelProperty;





/**
 * @author Sheng-ji Lau
 * @date 2018年3月17日下午3:11:37
 * @version
 */
public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated
     */
	
	
	@ApiModelProperty(value="订单id")
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.supplier
     *
     * @mbggenerated
     */
	@NotBlank
	@ApiModelProperty(value="供应商/客户名称")
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_no
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="采购/销售单号")
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="订单类型(采购 or销售)")
    private Short orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.contract_code
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="合同编号")
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.approval_status
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="审批状态")
    private Short approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.dispatching_type
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="配送方式")
	@NotNull
    private Short dispatchingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_type
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="付款方式")
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receive_warehouse
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货仓库")
    private String receiveWarehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.file_url
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="附件url")
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sender
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货人")
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sender_phone
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货人联系方式")
    private String senderPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.send_province
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货省")
    private String sendProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.send_city
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货市")
    private String sendCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.send_district
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货区")
    private String sendDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.send_address
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货详细地址")
    private String sendAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.send_time
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="发货时间")
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pack_require
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="包装要求")
    private String packRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receiver
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货人")
	@NotBlank
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receiver_phone
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货人联系方式")
	@NotBlank
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receiver_province
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货省")
	@NotBlank
    private String receiverProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receiver_city
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货市")
	@NotBlank
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receive_district
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货区")
	@NotBlank
    private String receiveDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.receive_address
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="收货详细地址")
	@NotBlank
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.remarks
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="备注")
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.approval_start_date
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="审批开始日期")
    private Date approvalStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.approval_end_date
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="审批结束日期")
    private Date approvalEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.group_id
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="所属业务组")
	@NotNull
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.company_id
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="所属公司id")
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_user_id
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="创建人id")
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_serial_no
     *
     * @mbggenerated
     */
	@ApiModelProperty(value="订单流水号")
    private String orderSerialNo;
	
	
	@ApiModelProperty(value="收货时间")
	private Date receiveTime;
	
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 13333L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.supplier
     *
     * @return the value of t_order.supplier
     *
     * @mbggenerated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.supplier
     *
     * @param supplier the value for t_order.supplier
     *
     * @mbggenerated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_no
     *
     * @return the value of t_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_no
     *
     * @param orderNo the value for t_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_type
     *
     * @return the value of t_order.order_type
     *
     * @mbggenerated
     */
    public Short getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_type
     *
     * @param orderType the value for t_order.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Short orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.contract_code
     *
     * @return the value of t_order.contract_code
     *
     * @mbggenerated
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.contract_code
     *
     * @param contractCode the value for t_order.contract_code
     *
     * @mbggenerated
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.approval_status
     *
     * @return the value of t_order.approval_status
     *
     * @mbggenerated
     */
    public Short getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.approval_status
     *
     * @param approvalStatus the value for t_order.approval_status
     *
     * @mbggenerated
     */
    public void setApprovalStatus(Short approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.dispatching_type
     *
     * @return the value of t_order.dispatching_type
     *
     * @mbggenerated
     */
    public Short getDispatchingType() {
        return dispatchingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.dispatching_type
     *
     * @param dispatchingType the value for t_order.dispatching_type
     *
     * @mbggenerated
     */
    public void setDispatchingType(Short dispatchingType) {
        this.dispatchingType = dispatchingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_type
     *
     * @return the value of t_order.pay_type
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_type
     *
     * @param payType the value for t_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receive_warehouse
     *
     * @return the value of t_order.receive_warehouse
     *
     * @mbggenerated
     */
    public String getReceiveWarehouse() {
        return receiveWarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receive_warehouse
     *
     * @param receiveWarehouse the value for t_order.receive_warehouse
     *
     * @mbggenerated
     */
    public void setReceiveWarehouse(String receiveWarehouse) {
        this.receiveWarehouse = receiveWarehouse == null ? null : receiveWarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.file_url
     *
     * @return the value of t_order.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.file_url
     *
     * @param fileUrl the value for t_order.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.sender
     *
     * @return the value of t_order.sender
     *
     * @mbggenerated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.sender
     *
     * @param sender the value for t_order.sender
     *
     * @mbggenerated
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.sender_phone
     *
     * @return the value of t_order.sender_phone
     *
     * @mbggenerated
     */
    public String getSenderPhone() {
        return senderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.sender_phone
     *
     * @param senderPhone the value for t_order.sender_phone
     *
     * @mbggenerated
     */
    public void setSenderPhone(String senderPhone) {
        this.senderPhone = senderPhone == null ? null : senderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_province
     *
     * @return the value of t_order.send_province
     *
     * @mbggenerated
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_province
     *
     * @param sendProvince the value for t_order.send_province
     *
     * @mbggenerated
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_city
     *
     * @return the value of t_order.send_city
     *
     * @mbggenerated
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_city
     *
     * @param sendCity the value for t_order.send_city
     *
     * @mbggenerated
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_district
     *
     * @return the value of t_order.send_district
     *
     * @mbggenerated
     */
    public String getSendDistrict() {
        return sendDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_district
     *
     * @param sendDistrict the value for t_order.send_district
     *
     * @mbggenerated
     */
    public void setSendDistrict(String sendDistrict) {
        this.sendDistrict = sendDistrict == null ? null : sendDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_address
     *
     * @return the value of t_order.send_address
     *
     * @mbggenerated
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_address
     *
     * @param sendAddress the value for t_order.send_address
     *
     * @mbggenerated
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.send_time
     *
     * @return the value of t_order.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.send_time
     *
     * @param sendTime the value for t_order.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pack_require
     *
     * @return the value of t_order.pack_require
     *
     * @mbggenerated
     */
    public String getPackRequire() {
        return packRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pack_require
     *
     * @param packRequire the value for t_order.pack_require
     *
     * @mbggenerated
     */
    public void setPackRequire(String packRequire) {
        this.packRequire = packRequire == null ? null : packRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receiver
     *
     * @return the value of t_order.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receiver
     *
     * @param receiver the value for t_order.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receiver_phone
     *
     * @return the value of t_order.receiver_phone
     *
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receiver_phone
     *
     * @param receiverPhone the value for t_order.receiver_phone
     *
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receiver_province
     *
     * @return the value of t_order.receiver_province
     *
     * @mbggenerated
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receiver_province
     *
     * @param receiverProvince the value for t_order.receiver_province
     *
     * @mbggenerated
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince == null ? null : receiverProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receiver_city
     *
     * @return the value of t_order.receiver_city
     *
     * @mbggenerated
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receiver_city
     *
     * @param receiverCity the value for t_order.receiver_city
     *
     * @mbggenerated
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receive_district
     *
     * @return the value of t_order.receive_district
     *
     * @mbggenerated
     */
    public String getReceiveDistrict() {
        return receiveDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receive_district
     *
     * @param receiveDistrict the value for t_order.receive_district
     *
     * @mbggenerated
     */
    public void setReceiveDistrict(String receiveDistrict) {
        this.receiveDistrict = receiveDistrict == null ? null : receiveDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.receive_address
     *
     * @return the value of t_order.receive_address
     *
     * @mbggenerated
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.receive_address
     *
     * @param receiveAddress the value for t_order.receive_address
     *
     * @mbggenerated
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.remarks
     *
     * @return the value of t_order.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.remarks
     *
     * @param remarks the value for t_order.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.approval_start_date
     *
     * @return the value of t_order.approval_start_date
     *
     * @mbggenerated
     */
    public Date getApprovalStartDate() {
        return approvalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.approval_start_date
     *
     * @param approvalStartDate the value for t_order.approval_start_date
     *
     * @mbggenerated
     */
    public void setApprovalStartDate(Date approvalStartDate) {
        this.approvalStartDate = approvalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.approval_end_date
     *
     * @return the value of t_order.approval_end_date
     *
     * @mbggenerated
     */
    public Date getApprovalEndDate() {
        return approvalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.approval_end_date
     *
     * @param approvalEndDate the value for t_order.approval_end_date
     *
     * @mbggenerated
     */
    public void setApprovalEndDate(Date approvalEndDate) {
        this.approvalEndDate = approvalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.group_id
     *
     * @return the value of t_order.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.group_id
     *
     * @param groupId the value for t_order.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.company_id
     *
     * @return the value of t_order.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.company_id
     *
     * @param companyId the value for t_order.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_user_id
     *
     * @return the value of t_order.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_user_id
     *
     * @param createUserId the value for t_order.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_serial_no
     *
     * @return the value of t_order.order_serial_no
     *
     * @mbggenerated
     */
    public String getOrderSerialNo() {
        return orderSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_serial_no
     *
     * @param orderSerialNo the value for t_order.order_serial_no
     *
     * @mbggenerated
     */
    public void setOrderSerialNo(String orderSerialNo) {
        this.orderSerialNo = orderSerialNo == null ? null : orderSerialNo.trim();
    }

	public Date getReceiveTime() {
		return receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

 

   

   
}