spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.37.21.24:3306/clms_ct_db?useUnicode=true&characterEncoding=utf-8
    name: root
    password: Root123!
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
logging:
  config: classpath:logback-config.xml