package com.lcdt.items.dao;

import com.lcdt.items.model.ItemsInfo;

import java.util.List;

public interface ItemsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int insert(ItemsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    ItemsInfo selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    List<ItemsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemsInfo record);
}