package com.lcdt.items.dao;

import com.lcdt.items.model.ItemsExtendProperty;

import java.util.List;

public interface ItemsExtendPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_extend_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long itemTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_extend_property
     *
     * @mbg.generated
     */
    int insert(ItemsExtendProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_extend_property
     *
     * @mbg.generated
     */
    ItemsExtendProperty selectByPrimaryKey(Long itemTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_extend_property
     *
     * @mbg.generated
     */
    List<ItemsExtendProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_extend_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemsExtendProperty record);
}