package com.lcdt.items.dao;

import com.lcdt.items.model.ItemSpecKeyValue;

import java.util.List;
import java.util.Map;

public interface ItemSpecKeyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_spec_key_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long spkvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_spec_key_value
     *
     * @mbg.generated
     */
    int insert(ItemSpecKeyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_spec_key_value
     *
     * @mbg.generated
     */
    ItemSpecKeyValue selectByPrimaryKey(Long spkvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_spec_key_value
     *
     * @mbg.generated
     */
    List<ItemSpecKeyValue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_item_spec_key_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemSpecKeyValue record);

    /**
     * 批量插入商品自定义规格
     * @param itemSpecKeyValueList
     * @return
     */
    int insertForBatch(List<ItemSpecKeyValue> itemSpecKeyValueList);

    /**
     * 根据子商品subItemId 和 companyId 删除规格
     * @param itemSpecKeyValue
     * @return
     */
    int deleteBySubItemIdAndCompanyId(ItemSpecKeyValue itemSpecKeyValue);

    /**
     * 根据subItemIds 和 companyId 批量删除
     * @param map
     * @return
     */
    int deleteBySubItemIds(Map<String,Object> map);

    /**
     * 根据子商品 subItemId 查询
     * @param subItemId
     * @return
     */
    List<ItemSpecKeyValue> selectSpecKeyValueBySubItemId(Long subItemId);
}