package com.lcdt.items.dao;

import com.lcdt.items.model.ItemsSpecifical;

import java.util.List;

public interface ItemsSpecificalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_specifical
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long specId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_specifical
     *
     * @mbg.generated
     */
    int insert(ItemsSpecifical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_specifical
     *
     * @mbg.generated
     */
    ItemsSpecifical selectByPrimaryKey(Long specId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_specifical
     *
     * @mbg.generated
     */
    List<ItemsSpecifical> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_specifical
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemsSpecifical record);

    /**
     * 查询此企业下的子商品规格
     *
     * @param companyId
     * @return
     */
    List<ItemsSpecifical> selectItemsSpecificalListByCompanyId(Long companyId);
}