package com.lcdt.items.dao;

import com.lcdt.items.model.ItemsInfo;
import com.lcdt.items.model.ItemsInfoDao;

import java.util.List;
import java.util.Map;

public interface ItemsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int insert(ItemsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    ItemsInfo selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    List<ItemsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_items_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemsInfo record);

    /**
     * 根据 itemId 和 companyId 查询
     * @param itemsInfo
     * @return
     */
    ItemsInfo selectByItemIdAndCompanyId(ItemsInfo itemsInfo);

    /**
     * 根据商品编码和企业ID查询商品
     * @param itemsInfo
     * @return
     */
    ItemsInfo selectByCodeAndCompanyId(ItemsInfo itemsInfo);
    /**
     * 根据相关查询条件查询相关
     * @param itemsInfo
     * @return
     */
    List<ItemsInfoDao> selectByCondition(ItemsInfo itemsInfo);

    /**
     * 根据itemId 和 companyId 查询
     * @param itemsInfo
     * @return
     */
    ItemsInfoDao selectIetmsInfoDetails(ItemsInfo itemsInfo);


    /**
     * 根据 itemId 和 companyId 删除商品
     * @param itemsInfo
     * @return
     */
    int deleteByItemIdAndCompanyId(ItemsInfo itemsInfo);

    /**
     * 根据 itemId 和 companyId 更新商品
     * @param itemsInfo
     * @return
     */
    int updateByItemIdAndCompanyId(ItemsInfo itemsInfo);

    /**
     * 根据相关查询条件查询相关
     * @param itemsInfo
     * @return
     */
    List<ItemsInfoDao> selectByItemsInfo(ItemsInfo itemsInfo);

    /**
     * 根据单位id
     * @param itemsInfo
     * @return
     */
    List<ItemsInfo> selectByItemsCalUnitId(ItemsInfo itemsInfo);

    /**
     * 根据分类id
     * @param map
     * @return
     */
    List<ItemsInfo> selectByClassifyIdCodeAndCompanyId(Map map);
}