package com.lcdt.items.dao;

import com.lcdt.items.model.SubItemsInfo;
import com.lcdt.items.model.SubItemsInfoDao;

import java.util.List;

public interface SubItemsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_items_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long subItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_items_info
     *
     * @mbggenerated
     */
    int insert(SubItemsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_items_info
     *
     * @mbggenerated
     */
    SubItemsInfo selectByPrimaryKey(Long subItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_items_info
     *
     * @mbggenerated
     */
    List<SubItemsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sub_items_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubItemsInfo record);

    /**
     * 根据主商品 itemId 查询此主商品下的所有子商品
     *
     * @param itemId
     * @return
     */
    List<SubItemsInfo> selectSubItemsInfoListByItemId(Long itemId);

    /**
     * 根据商品itemId删除子商品
     * @param itemId
     * @return
     */
    int deleteSubItemsInfoByItemId(Long itemId);

    /**
     * 批量插入数据
     * @param subItemsInfoList
     * @return
     */
    int insertByBatch(List<SubItemsInfo> subItemsInfoList);

    /**
     * 查询列表
     * @param itemId
     * @return
     */
    List<SubItemsInfoDao> selectSubAndSpecAndPropListByItemId(Long itemId);
}