package com.lcdt.wms.permission.model;

public class WmsPermissionGroupRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_up_group_permission.relation_id
     *
     * @mbg.generated
     */
    private Integer relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_up_group_permission.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_up_group_permission.permission_id
     *
     * @mbg.generated
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_up_group_permission.relation_id
     *
     * @return the value of t_up_group_permission.relation_id
     *
     * @mbg.generated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_up_group_permission.relation_id
     *
     * @param relationId the value for t_up_group_permission.relation_id
     *
     * @mbg.generated
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_up_group_permission.group_id
     *
     * @return the value of t_up_group_permission.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_up_group_permission.group_id
     *
     * @param groupId the value for t_up_group_permission.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_up_group_permission.permission_id
     *
     * @return the value of t_up_group_permission.permission_id
     *
     * @mbg.generated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_up_group_permission.permission_id
     *
     * @param permissionId the value for t_up_group_permission.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}