package com.lcdt.client.dao;

import com.lcdt.client.model.ClientLinkman;

import java.util.List;

public interface ClientLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_linkman
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long linkmanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_linkman
     *
     * @mbg.generated
     */
    int insert(ClientLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_linkman
     *
     * @mbg.generated
     */
    ClientLinkman selectByPrimaryKey(Long linkmanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_linkman
     *
     * @mbg.generated
     */
    List<ClientLinkman> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_linkman
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClientLinkman record);

    /**
     * 根据myClientId查询相关联系人
     * @param myClientId
     * @return
     */
    List<ClientLinkman> selectByClientId(Long myClientId);
}