package com.lcdt.userinfo.dao;

import com.lcdt.userinfo.model.CompanyMember;

import java.util.List;
import java.util.Map;

public interface CompanyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_member
     *
     * @mbg.generated
     */
    int insert(CompanyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_member
     *
     * @mbg.generated
     */
    CompanyMember selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_member
     *
     * @mbg.generated
     */
    List<CompanyMember> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyMember record);

    /***
     *  企业-用户 关系查询
     * @return
     */
    List<CompanyMember> selectByCondition(Map map);


}