package com.lcdt.userinfo.dao;


import com.lcdt.userinfo.model.Company;

import java.util.List;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_company
     *
     * @mbg.generated
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_company
     *
     * @mbg.generated
     */
    Company selectByPrimaryKey(Long compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_company
     *
     * @mbg.generated
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Company record);


    Company selectByCondition(Company record);

}