package com.lcdt.userinfo.dao;

import com.lcdt.userinfo.model.GoodsFeildsTemplate;

import java.util.List;

public interface GoodsFeildsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_fields_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodFieldsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_fields_template
     *
     * @mbg.generated
     */
    int insert(GoodsFeildsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_fields_template
     *
     * @mbg.generated
     */
    GoodsFeildsTemplate selectByPrimaryKey(Long goodFieldsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_fields_template
     *
     * @mbg.generated
     */
    List<GoodsFeildsTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_fields_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsFeildsTemplate record);
}