package com.lcdt.userinfo.dao;

import com.lcdt.userinfo.model.UserGroupRelation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserGroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long relationId);

    int deleteByUserGroupRelation(UserGroupRelation record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user_group
     *
     * @mbg.generated
     */
    int insert(UserGroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user_group
     *
     * @mbg.generated
     */
    UserGroupRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user_group
     *
     * @mbg.generated
     */
    List<UserGroupRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroupRelation record);


    List<UserGroupRelation> selectByGroupId(Long groupId);

    List<UserGroupRelation> selectByUserCompany(@Param("userId") Long userId, @Param("companyId") Long companyId);

    void deleteNotInGroups(Long userId, Long companyId, List<Long> groups);

    void insertGroups(Long userId, Long companyId, List<Long> groups);

    List<UserGroupRelation> selectByUserIdAndCmpId(UserGroupRelation userGroupRelation);





}