package com.lcdt.userinfo.dao;

import com.aliyun.openservices.ons.api.Admin;
import com.lcdt.userinfo.model.AdminUser;
import com.lcdt.userinfo.model.User;
import com.lcdt.userinfo.web.controller.api.admin.dto.AdminUserDto;
import com.lcdt.userinfo.web.dto.UserQueryDto;

import java.util.List;
import java.util.Map;

public interface UserMapper {


    List<AdminUserDto> selectByUserDto(UserQueryDto userQueryDto);

    List<AdminUser> selectManageUserByUserDto(UserQueryDto userQueryDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
    int updateByPrimaryKeyWithoutPwd(User record);
    /***
     * 通过手机号查询用户信息
     * @param phone
     * @return
     */
    User queryByUserPhone(String phone);


    User selectByPrimaryKeyWithoutPwd(Long userId);


    /***
     * 获取组下的员工
     * @return
     */
    List<User> selectUser4Group(Map m);

    /***
     * 根据企业ID获取企业创建者
     * @param compId
     * @return
     */
    User compCreateUserByCompId(Long compId);


}