package com.lcdt.goods.model;

public class GoodsPropertyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_property_value.property_value_id
     *
     * @mbg.generated
     */
    private Long propertyValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_property_value.goods_property_id
     *
     * @mbg.generated
     */
    private Long goodsPropertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_property_value.property_name
     *
     * @mbg.generated
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_property_value.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_property_value.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_property_value.property_value_id
     *
     * @return the value of t_goods_property_value.property_value_id
     *
     * @mbg.generated
     */
    public Long getPropertyValueId() {
        return propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_property_value.property_value_id
     *
     * @param propertyValueId the value for t_goods_property_value.property_value_id
     *
     * @mbg.generated
     */
    public void setPropertyValueId(Long propertyValueId) {
        this.propertyValueId = propertyValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_property_value.goods_property_id
     *
     * @return the value of t_goods_property_value.goods_property_id
     *
     * @mbg.generated
     */
    public Long getGoodsPropertyId() {
        return goodsPropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_property_value.goods_property_id
     *
     * @param goodsPropertyId the value for t_goods_property_value.goods_property_id
     *
     * @mbg.generated
     */
    public void setGoodsPropertyId(Long goodsPropertyId) {
        this.goodsPropertyId = goodsPropertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_property_value.property_name
     *
     * @return the value of t_goods_property_value.property_name
     *
     * @mbg.generated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_property_value.property_name
     *
     * @param propertyName the value for t_goods_property_value.property_name
     *
     * @mbg.generated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_property_value.value
     *
     * @return the value of t_goods_property_value.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_property_value.value
     *
     * @param value the value for t_goods_property_value.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_property_value.company_id
     *
     * @return the value of t_goods_property_value.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_property_value.company_id
     *
     * @param companyId the value for t_goods_property_value.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}