package com.lcdt.userinfo.model;

import java.util.Date;

public class CompanyMember implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.reg_dt
     *
     * @mbg.generated
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.depart_ids
     *
     * @mbg.generated
     */
    private String departIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.role_ids
     *
     * @mbg.generated
     */
    private String roleIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.positions
     *
     * @mbg.generated
     */
    private String positions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.user_valid
     *
     * @mbg.generated
     */
    private Integer userValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.login_dt
     *
     * @mbg.generated
     */
    private Date loginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.depart_ids_bak
     *
     * @mbg.generated
     */
    private String departIdsBak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.depart_names
     *
     * @mbg.generated
     */
    private String departNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.role_ids_bak
     *
     * @mbg.generated
     */
    private String roleIdsBak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column front_member.role_names
     *
     * @mbg.generated
     */
    private String roleNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.member_id
     *
     * @return the value of front_member.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.member_id
     *
     * @param memberId the value for front_member.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.user_id
     *
     * @return the value of front_member.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.user_id
     *
     * @param userId the value for front_member.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.company_id
     *
     * @return the value of front_member.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.company_id
     *
     * @param companyId the value for front_member.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.company_name
     *
     * @return the value of front_member.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.company_name
     *
     * @param companyName the value for front_member.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.reg_dt
     *
     * @return the value of front_member.reg_dt
     *
     * @mbg.generated
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.reg_dt
     *
     * @param regDt the value for front_member.reg_dt
     *
     * @mbg.generated
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.depart_ids
     *
     * @return the value of front_member.depart_ids
     *
     * @mbg.generated
     */
    public String getDepartIds() {
        return departIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.depart_ids
     *
     * @param departIds the value for front_member.depart_ids
     *
     * @mbg.generated
     */
    public void setDepartIds(String departIds) {
        this.departIds = departIds == null ? null : departIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.role_ids
     *
     * @return the value of front_member.role_ids
     *
     * @mbg.generated
     */
    public String getRoleIds() {
        return roleIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.role_ids
     *
     * @param roleIds the value for front_member.role_ids
     *
     * @mbg.generated
     */
    public void setRoleIds(String roleIds) {
        this.roleIds = roleIds == null ? null : roleIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.positions
     *
     * @return the value of front_member.positions
     *
     * @mbg.generated
     */
    public String getPositions() {
        return positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.positions
     *
     * @param positions the value for front_member.positions
     *
     * @mbg.generated
     */
    public void setPositions(String positions) {
        this.positions = positions == null ? null : positions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.user_valid
     *
     * @return the value of front_member.user_valid
     *
     * @mbg.generated
     */
    public Integer getUserValid() {
        return userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.user_valid
     *
     * @param userValid the value for front_member.user_valid
     *
     * @mbg.generated
     */
    public void setUserValid(Integer userValid) {
        this.userValid = userValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.login_dt
     *
     * @return the value of front_member.login_dt
     *
     * @mbg.generated
     */
    public Date getLoginDt() {
        return loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.login_dt
     *
     * @param loginDt the value for front_member.login_dt
     *
     * @mbg.generated
     */
    public void setLoginDt(Date loginDt) {
        this.loginDt = loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.depart_ids_bak
     *
     * @return the value of front_member.depart_ids_bak
     *
     * @mbg.generated
     */
    public String getDepartIdsBak() {
        return departIdsBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.depart_ids_bak
     *
     * @param departIdsBak the value for front_member.depart_ids_bak
     *
     * @mbg.generated
     */
    public void setDepartIdsBak(String departIdsBak) {
        this.departIdsBak = departIdsBak == null ? null : departIdsBak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.depart_names
     *
     * @return the value of front_member.depart_names
     *
     * @mbg.generated
     */
    public String getDepartNames() {
        return departNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.depart_names
     *
     * @param departNames the value for front_member.depart_names
     *
     * @mbg.generated
     */
    public void setDepartNames(String departNames) {
        this.departNames = departNames == null ? null : departNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.role_ids_bak
     *
     * @return the value of front_member.role_ids_bak
     *
     * @mbg.generated
     */
    public String getRoleIdsBak() {
        return roleIdsBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.role_ids_bak
     *
     * @param roleIdsBak the value for front_member.role_ids_bak
     *
     * @mbg.generated
     */
    public void setRoleIdsBak(String roleIdsBak) {
        this.roleIdsBak = roleIdsBak == null ? null : roleIdsBak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column front_member.role_names
     *
     * @return the value of front_member.role_names
     *
     * @mbg.generated
     */
    public String getRoleNames() {
        return roleNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column front_member.role_names
     *
     * @param roleNames the value for front_member.role_names
     *
     * @mbg.generated
     */
    public void setRoleNames(String roleNames) {
        this.roleNames = roleNames == null ? null : roleNames.trim();
    }

    @Override
    public String toString() {
        return "CompanyMember{" +
                "memberId=" + memberId +
                ", userId=" + userId +
                ", companyId=" + companyId +
                ", companyName='" + companyName + '\'' +
                ", regDt=" + regDt +
                ", departIds='" + departIds + '\'' +
                ", roleIds='" + roleIds + '\'' +
                ", positions='" + positions + '\'' +
                ", userValid=" + userValid +
                ", loginDt=" + loginDt +
                ", departIdsBak='" + departIdsBak + '\'' +
                ", departNames='" + departNames + '\'' +
                ", roleIdsBak='" + roleIdsBak + '\'' +
                ", roleNames='" + roleNames + '\'' +
                '}';
    }
}