package com.lcdt.userinfo.model;

public class CompanyCertificate implements java.io.Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_company_certificate.certi_id
     *
     * @mbg.generated
     */
    private Long certiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_company_certificate.comp_id
     *
     * @mbg.generated
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_company_certificate.identity_front
     *
     * @mbg.generated
     */
    private String identityFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_company_certificate.identity_back
     *
     * @mbg.generated
     */
    private String identityBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_company_certificate.three_certificates
     *
     * @mbg.generated
     */
    private String threeCertificates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_company_certificate.certi_id
     *
     * @return the value of t_uc_company_certificate.certi_id
     *
     * @mbg.generated
     */
    public Long getCertiId() {
        return certiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_company_certificate.certi_id
     *
     * @param certiId the value for t_uc_company_certificate.certi_id
     *
     * @mbg.generated
     */
    public void setCertiId(Long certiId) {
        this.certiId = certiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_company_certificate.comp_id
     *
     * @return the value of t_uc_company_certificate.comp_id
     *
     * @mbg.generated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_company_certificate.comp_id
     *
     * @param compId the value for t_uc_company_certificate.comp_id
     *
     * @mbg.generated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_company_certificate.identity_front
     *
     * @return the value of t_uc_company_certificate.identity_front
     *
     * @mbg.generated
     */
    public String getIdentityFront() {
        return identityFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_company_certificate.identity_front
     *
     * @param identityFront the value for t_uc_company_certificate.identity_front
     *
     * @mbg.generated
     */
    public void setIdentityFront(String identityFront) {
        this.identityFront = identityFront == null ? null : identityFront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_company_certificate.identity_back
     *
     * @return the value of t_uc_company_certificate.identity_back
     *
     * @mbg.generated
     */
    public String getIdentityBack() {
        return identityBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_company_certificate.identity_back
     *
     * @param identityBack the value for t_uc_company_certificate.identity_back
     *
     * @mbg.generated
     */
    public void setIdentityBack(String identityBack) {
        this.identityBack = identityBack == null ? null : identityBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_company_certificate.three_certificates
     *
     * @return the value of t_uc_company_certificate.three_certificates
     *
     * @mbg.generated
     */
    public String getThreeCertificates() {
        return threeCertificates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_company_certificate.three_certificates
     *
     * @param threeCertificates the value for t_uc_company_certificate.three_certificates
     *
     * @mbg.generated
     */
    public void setThreeCertificates(String threeCertificates) {
        this.threeCertificates = threeCertificates == null ? null : threeCertificates.trim();
    }
}