package com.lcdt.userinfo.model;

import com.lcdt.converter.ResponseData;

import java.util.Date;

public class Group implements java.io.Serializable,ResponseData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.is_valid
     *
     * @mbg.generated
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.group_remark
     *
     * @mbg.generated
     */
    private String groupRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uc_group.creat_time
     *
     * @mbg.generated
     */
    private Long createId;
    private String createName;

    public Long getCreateId() {
        return createId;
    }

    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    private Date createDate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_group.group_id
     *
     * @return the value of t_uc_group.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_group.group_id
     *
     * @param groupId the value for t_uc_group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_group.group_name
     *
     * @return the value of t_uc_group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_group.group_name
     *
     * @param groupName the value for t_uc_group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_group.company_id
     *
     * @return the value of t_uc_group.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_group.company_id
     *
     * @param companyId the value for t_uc_group.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_group.is_valid
     *
     * @return the value of t_uc_group.is_valid
     *
     * @mbg.generated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_group.is_valid
     *
     * @param isValid the value for t_uc_group.is_valid
     *
     * @mbg.generated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uc_group.group_remark
     *
     * @return the value of t_uc_group.group_remark
     *
     * @mbg.generated
     */
    public String getGroupRemark() {
        return groupRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uc_group.group_remark
     *
     * @param groupRemark the value for t_uc_group.group_remark
     *
     * @mbg.generated
     */
    public void setGroupRemark(String groupRemark) {
        this.groupRemark = groupRemark == null ? null : groupRemark.trim();
    }




    public Boolean getValid() {
        return isValid;
    }

    public void setValid(Boolean valid) {
        isValid = valid;
    }
}