package com.lcdt.userinfo.model;

import java.util.Date;

public class MyClientLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.my_client_linkman_id
     *
     * @mbg.generated
     */
    private Long myClientLinkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.my_client_id
     *
     * @mbg.generated
     */
    private Long myClientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_client_linkman.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.my_client_linkman_id
     *
     * @return the value of t_my_client_linkman.my_client_linkman_id
     *
     * @mbg.generated
     */
    public Long getMyClientLinkmanId() {
        return myClientLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.my_client_linkman_id
     *
     * @param myClientLinkmanId the value for t_my_client_linkman.my_client_linkman_id
     *
     * @mbg.generated
     */
    public void setMyClientLinkmanId(Long myClientLinkmanId) {
        this.myClientLinkmanId = myClientLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.my_client_id
     *
     * @return the value of t_my_client_linkman.my_client_id
     *
     * @mbg.generated
     */
    public Long getMyClientId() {
        return myClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.my_client_id
     *
     * @param myClientId the value for t_my_client_linkman.my_client_id
     *
     * @mbg.generated
     */
    public void setMyClientId(Long myClientId) {
        this.myClientId = myClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.name
     *
     * @return the value of t_my_client_linkman.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.name
     *
     * @param name the value for t_my_client_linkman.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.duty
     *
     * @return the value of t_my_client_linkman.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.duty
     *
     * @param duty the value for t_my_client_linkman.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.mobile
     *
     * @return the value of t_my_client_linkman.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.mobile
     *
     * @param mobile the value for t_my_client_linkman.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.mail
     *
     * @return the value of t_my_client_linkman.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.mail
     *
     * @param mail the value for t_my_client_linkman.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.birthday
     *
     * @return the value of t_my_client_linkman.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.birthday
     *
     * @param birthday the value for t_my_client_linkman.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.sex
     *
     * @return the value of t_my_client_linkman.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.sex
     *
     * @param sex the value for t_my_client_linkman.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.province
     *
     * @return the value of t_my_client_linkman.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.province
     *
     * @param province the value for t_my_client_linkman.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.city
     *
     * @return the value of t_my_client_linkman.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.city
     *
     * @param city the value for t_my_client_linkman.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.county
     *
     * @return the value of t_my_client_linkman.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.county
     *
     * @param county the value for t_my_client_linkman.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.detail_address
     *
     * @return the value of t_my_client_linkman.detail_address
     *
     * @mbg.generated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.detail_address
     *
     * @param detailAddress the value for t_my_client_linkman.detail_address
     *
     * @mbg.generated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.remark
     *
     * @return the value of t_my_client_linkman.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.remark
     *
     * @param remark the value for t_my_client_linkman.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_client_linkman.company_id
     *
     * @return the value of t_my_client_linkman.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_client_linkman.company_id
     *
     * @param companyId the value for t_my_client_linkman.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}