package com.lcdt.traffic.dao;

import com.lcdt.traffic.model.SnatchGoodsDetail;

import java.util.List;

public interface SnatchGoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_snatch_goods_detail
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int deleteByPrimaryKey(Long snatchGoodsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_snatch_goods_detail
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int insert(SnatchGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_snatch_goods_detail
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    SnatchGoodsDetail selectByPrimaryKey(Long snatchGoodsDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_snatch_goods_detail
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    List<SnatchGoodsDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_snatch_goods_detail
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int updateByPrimaryKey(SnatchGoodsDetail record);
}