package com.lcdt.traffic.dao;

import com.lcdt.traffic.model.WaybillItems;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WaybillItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_items
     *
     * @mbg.generated Wed Dec 20 17:19:52 CST 2017
     */
    int deleteByPrimaryKey(@Param("companyId") Long companyId,@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_items
     *
     * @mbg.generated Wed Dec 20 17:19:52 CST 2017
     */
    int insert(WaybillItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_items
     *
     * @mbg.generated Wed Dec 20 17:19:52 CST 2017
     */
    WaybillItems selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_items
     *
     * @mbg.generated Wed Dec 20 17:19:52 CST 2017
     */
    List<WaybillItems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_items
     *
     * @mbg.generated Wed Dec 20 17:19:52 CST 2017
     */
    int updateByPrimaryKey(WaybillItems record);

    /**
     * 批量插入货详细
     * @param list
     * @return
     */
    int insertForBatch(List<WaybillItems> list);

    /**
     * 批量修改货物详细
     * @param list
     * @return
     */
    int updateForBatch(List<WaybillItems> list);

    /**
     * 获取单个运单货物详情
     * @param waybillId
     * @return
     */
    List<WaybillItems> selectByWaybillId(Long waybillId);
}