package com.lcdt.traffic.dao;

import com.lcdt.traffic.dto.ClientPlanDto;
import com.lcdt.traffic.model.WaybillPlan;

import java.util.List;
import java.util.Map;

public interface WaybillPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_plan
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int deleteByPrimaryKey(Long waybillPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_plan
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int insert(WaybillPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_plan
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    WaybillPlan selectByPrimaryKey(Long waybillPlanId, Long companyId, Short isDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_waybill_plan
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    int updateByPrimaryKey(WaybillPlan record);

    int updateWaybillPlan(WaybillPlan record);

    /***
     * 根据条件查询计划
     * @param map
     * @return
     */
    List<WaybillPlan> selectByCondition(Map map);


    /***
     * 客户计划-竞价中
     */
    List<ClientPlanDto> clientPlan4Bidding(Map map);


    /***
     * 客户计划-已报价
     */
    List<ClientPlanDto> clientPlanList4Offer(Map map);

    /***
     * 客户计划-已错过
     */
    List<ClientPlanDto> clientPlanList4Pass(Map map);


    /***
     * 客户计划-派车中
     * @return
     */
    List<ClientPlanDto> clientPlanList4VehicleDoing(Map map);


    /***
     * 客户计划-已派车
     */
    List<ClientPlanDto> clientPlanList4VehicleHave(Map map);


    /***
     * 客户计划-已取消
     * @param map
     * @return
     */
    List<ClientPlanDto> clientPlanList4Cancel(Map map);


}