package com.lcdt.traffic.model;

import com.lcdt.converter.ResponseData;

import java.util.Date;
import java.util.List;

public class SnatchGoods implements java.io.Serializable,ResponseData {

    private String vehicleNum;//司机报价车辆


    private String vehicleType;

    private double vehicleLoad;

    private double vehicleLength;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.snatch_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long snatchGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long waybillPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.offer_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date offerDate;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.offer_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long offerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.offer_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String offerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.offer_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String offerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.is_using
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short isUsing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short isDeleted;


    public Long getPlanCompanyId() {
        return planCompanyId;
    }

    public void setPlanCompanyId(Long planCompanyId) {
        this.planCompanyId = planCompanyId;
    }

    private Long planCompanyId;


    public List<SnatchGoodsDetail> getSnatchGoodsDetailList() {
        return snatchGoodsDetailList;
    }

    public void setSnatchGoodsDetailList(List<SnatchGoodsDetail> snatchGoodsDetailList) {
        this.snatchGoodsDetailList = snatchGoodsDetailList;
    }

    private List<SnatchGoodsDetail> snatchGoodsDetailList;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_snatch_goods_detail.offer_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String offerRemark;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.snatch_goods_id
     *
     * @return the value of t_snatch_goods.snatch_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getSnatchGoodsId() {
        return snatchGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.snatch_goods_id
     *
     * @param snatchGoodsId the value for t_snatch_goods.snatch_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSnatchGoodsId(Long snatchGoodsId) {
        this.snatchGoodsId = snatchGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.waybill_plan_id
     *
     * @return the value of t_snatch_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getWaybillPlanId() {
        return waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.waybill_plan_id
     *
     * @param waybillPlanId the value for t_snatch_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setWaybillPlanId(Long waybillPlanId) {
        this.waybillPlanId = waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.offer_date
     *
     * @return the value of t_snatch_goods.offer_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getOfferDate() {
        return offerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.offer_date
     *
     * @param offerDate the value for t_snatch_goods.offer_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setOfferDate(Date offerDate) {
        this.offerDate = offerDate;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.offer_id
     *
     * @return the value of t_snatch_goods.offer_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.offer_id
     *
     * @param offerId the value for t_snatch_goods.offer_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.offer_name
     *
     * @return the value of t_snatch_goods.offer_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.offer_name
     *
     * @param offerName the value for t_snatch_goods.offer_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName == null ? null : offerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.offer_phone
     *
     * @return the value of t_snatch_goods.offer_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getOfferPhone() {
        return offerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.offer_phone
     *
     * @param offerPhone the value for t_snatch_goods.offer_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setOfferPhone(String offerPhone) {
        this.offerPhone = offerPhone == null ? null : offerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.is_using
     *
     * @return the value of t_snatch_goods.is_using
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getIsUsing() {
        return isUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.is_using
     *
     * @param isUsing the value for t_snatch_goods.is_using
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setIsUsing(Short isUsing) {
        this.isUsing = isUsing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.company_id
     *
     * @return the value of t_snatch_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.company_id
     *
     * @param companyId the value for t_snatch_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.create_id
     *
     * @return the value of t_snatch_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.create_id
     *
     * @param createId the value for t_snatch_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.create_name
     *
     * @return the value of t_snatch_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.create_name
     *
     * @param createName the value for t_snatch_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.create_date
     *
     * @return the value of t_snatch_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.create_date
     *
     * @param createDate the value for t_snatch_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.update_id
     *
     * @return the value of t_snatch_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.update_id
     *
     * @param updateId the value for t_snatch_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.update_name
     *
     * @return the value of t_snatch_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.update_name
     *
     * @param updateName the value for t_snatch_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.update_time
     *
     * @return the value of t_snatch_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.update_time
     *
     * @param updateTime the value for t_snatch_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_snatch_goods.is_deleted
     *
     * @return the value of t_snatch_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_snatch_goods.is_deleted
     *
     * @param isDeleted the value for t_snatch_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getOfferRemark() {
        return offerRemark;
    }

    public void setOfferRemark(String offerRemark) {
        this.offerRemark = offerRemark;
    }

    public String getVehicleNum() {
        return vehicleNum;
    }

    public void setVehicleNum(String vehicleNum) {
        this.vehicleNum = vehicleNum;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    public double getVehicleLoad() {
        return vehicleLoad;
    }

    public void setVehicleLoad(double vehicleLoad) {
        this.vehicleLoad = vehicleLoad;
    }

    public double getVehicleLength() {
        return vehicleLength;
    }

    public void setVehicleLength(double vehicleLength) {
        this.vehicleLength = vehicleLength;
    }
}