package com.lcdt.traffic.model;

import com.lcdt.converter.ResponseData;

import java.util.Date;

public class SplitGoodsDetail implements java.io.Serializable,ResponseData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.split_goods_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long splitGoodsDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long splitGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.plan_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long planDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Float allotAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.fact_allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Float factAllotAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.freight_price
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Float freightPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.freight_total
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Float freightTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.detail_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String detailRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods_detail.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.split_goods_detail_id
     *
     * @return the value of t_split_goods_detail.split_goods_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getSplitGoodsDetailId() {
        return splitGoodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.split_goods_detail_id
     *
     * @param splitGoodsDetailId the value for t_split_goods_detail.split_goods_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSplitGoodsDetailId(Long splitGoodsDetailId) {
        this.splitGoodsDetailId = splitGoodsDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.split_goods_id
     *
     * @return the value of t_split_goods_detail.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getSplitGoodsId() {
        return splitGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.split_goods_id
     *
     * @param splitGoodsId the value for t_split_goods_detail.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSplitGoodsId(Long splitGoodsId) {
        this.splitGoodsId = splitGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.plan_detail_id
     *
     * @return the value of t_split_goods_detail.plan_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getPlanDetailId() {
        return planDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.plan_detail_id
     *
     * @param planDetailId the value for t_split_goods_detail.plan_detail_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setPlanDetailId(Long planDetailId) {
        this.planDetailId = planDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.allot_amount
     *
     * @return the value of t_split_goods_detail.allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Float getAllotAmount() {
        return allotAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.allot_amount
     *
     * @param allotAmount the value for t_split_goods_detail.allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setAllotAmount(Float allotAmount) {
        this.allotAmount = allotAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.fact_allot_amount
     *
     * @return the value of t_split_goods_detail.fact_allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Float getFactAllotAmount() {
        return factAllotAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.fact_allot_amount
     *
     * @param factAllotAmount the value for t_split_goods_detail.fact_allot_amount
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setFactAllotAmount(Float factAllotAmount) {
        this.factAllotAmount = factAllotAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.freight_price
     *
     * @return the value of t_split_goods_detail.freight_price
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Float getFreightPrice() {
        return freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.freight_price
     *
     * @param freightPrice the value for t_split_goods_detail.freight_price
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setFreightPrice(Float freightPrice) {
        this.freightPrice = freightPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.freight_total
     *
     * @return the value of t_split_goods_detail.freight_total
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Float getFreightTotal() {
        return freightTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.freight_total
     *
     * @param freightTotal the value for t_split_goods_detail.freight_total
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setFreightTotal(Float freightTotal) {
        this.freightTotal = freightTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.detail_remark
     *
     * @return the value of t_split_goods_detail.detail_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getDetailRemark() {
        return detailRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.detail_remark
     *
     * @param detailRemark the value for t_split_goods_detail.detail_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setDetailRemark(String detailRemark) {
        this.detailRemark = detailRemark == null ? null : detailRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.create_id
     *
     * @return the value of t_split_goods_detail.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.create_id
     *
     * @param createId the value for t_split_goods_detail.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.create_name
     *
     * @return the value of t_split_goods_detail.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.create_name
     *
     * @param createName the value for t_split_goods_detail.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.create_date
     *
     * @return the value of t_split_goods_detail.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.create_date
     *
     * @param createDate the value for t_split_goods_detail.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.update_id
     *
     * @return the value of t_split_goods_detail.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.update_id
     *
     * @param updateId the value for t_split_goods_detail.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.update_name
     *
     * @return the value of t_split_goods_detail.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.update_name
     *
     * @param updateName the value for t_split_goods_detail.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.update_time
     *
     * @return the value of t_split_goods_detail.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.update_time
     *
     * @param updateTime the value for t_split_goods_detail.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.is_deleted
     *
     * @return the value of t_split_goods_detail.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.is_deleted
     *
     * @param isDeleted the value for t_split_goods_detail.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods_detail.company_id
     *
     * @return the value of t_split_goods_detail.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods_detail.company_id
     *
     * @param companyId the value for t_split_goods_detail.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}