package com.lcdt.traffic.model;

import com.lcdt.converter.ResponseData;

import java.util.Date;

public class SplitGoods implements java.io.Serializable,ResponseData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long splitGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long waybillPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short carrierType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_collection_ids
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierCollectionIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_collection_names
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierCollectionNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_vehicle
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierVehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.transport_way
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short transportWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.split_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String splitRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long carrierCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_split_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long companyId;

    private Long groupId;


    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.split_goods_id
     *
     * @return the value of t_split_goods.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getSplitGoodsId() {
        return splitGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.split_goods_id
     *
     * @param splitGoodsId the value for t_split_goods.split_goods_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSplitGoodsId(Long splitGoodsId) {
        this.splitGoodsId = splitGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.waybill_plan_id
     *
     * @return the value of t_split_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getWaybillPlanId() {
        return waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.waybill_plan_id
     *
     * @param waybillPlanId the value for t_split_goods.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setWaybillPlanId(Long waybillPlanId) {
        this.waybillPlanId = waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_type
     *
     * @return the value of t_split_goods.carrier_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getCarrierType() {
        return carrierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_type
     *
     * @param carrierType the value for t_split_goods.carrier_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierType(Short carrierType) {
        this.carrierType = carrierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_collection_ids
     *
     * @return the value of t_split_goods.carrier_collection_ids
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierCollectionIds() {
        return carrierCollectionIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_collection_ids
     *
     * @param carrierCollectionIds the value for t_split_goods.carrier_collection_ids
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierCollectionIds(String carrierCollectionIds) {
        this.carrierCollectionIds = carrierCollectionIds == null ? null : carrierCollectionIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_collection_names
     *
     * @return the value of t_split_goods.carrier_collection_names
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierCollectionNames() {
        return carrierCollectionNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_collection_names
     *
     * @param carrierCollectionNames the value for t_split_goods.carrier_collection_names
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierCollectionNames(String carrierCollectionNames) {
        this.carrierCollectionNames = carrierCollectionNames == null ? null : carrierCollectionNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_phone
     *
     * @return the value of t_split_goods.carrier_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierPhone() {
        return carrierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_phone
     *
     * @param carrierPhone the value for t_split_goods.carrier_phone
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierPhone(String carrierPhone) {
        this.carrierPhone = carrierPhone == null ? null : carrierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_vehicle
     *
     * @return the value of t_split_goods.carrier_vehicle
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierVehicle() {
        return carrierVehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_vehicle
     *
     * @param carrierVehicle the value for t_split_goods.carrier_vehicle
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierVehicle(String carrierVehicle) {
        this.carrierVehicle = carrierVehicle == null ? null : carrierVehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.transport_way
     *
     * @return the value of t_split_goods.transport_way
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getTransportWay() {
        return transportWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.transport_way
     *
     * @param transportWay the value for t_split_goods.transport_way
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setTransportWay(Short transportWay) {
        this.transportWay = transportWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.split_remark
     *
     * @return the value of t_split_goods.split_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getSplitRemark() {
        return splitRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.split_remark
     *
     * @param splitRemark the value for t_split_goods.split_remark
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSplitRemark(String splitRemark) {
        this.splitRemark = splitRemark == null ? null : splitRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.create_id
     *
     * @return the value of t_split_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.create_id
     *
     * @param createId the value for t_split_goods.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.create_name
     *
     * @return the value of t_split_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.create_name
     *
     * @param createName the value for t_split_goods.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.create_date
     *
     * @return the value of t_split_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.create_date
     *
     * @param createDate the value for t_split_goods.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.update_id
     *
     * @return the value of t_split_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.update_id
     *
     * @param updateId the value for t_split_goods.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.update_name
     *
     * @return the value of t_split_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.update_name
     *
     * @param updateName the value for t_split_goods.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.update_time
     *
     * @return the value of t_split_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.update_time
     *
     * @param updateTime the value for t_split_goods.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.is_deleted
     *
     * @return the value of t_split_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.is_deleted
     *
     * @param isDeleted the value for t_split_goods.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.carrier_company_id
     *
     * @return the value of t_split_goods.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCarrierCompanyId() {
        return carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.carrier_company_id
     *
     * @param carrierCompanyId the value for t_split_goods.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierCompanyId(Long carrierCompanyId) {
        this.carrierCompanyId = carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_split_goods.company_id
     *
     * @return the value of t_split_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_split_goods.company_id
     *
     * @param companyId the value for t_split_goods.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}