package com.lcdt.traffic.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lcdt.converter.ResponseData;

import java.io.Serializable;
import java.util.Date;

public class Waybill implements Serializable ,ResponseData{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.waybill_plan_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long waybillPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.split_goods_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long splitGoodsId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.waybill_code
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String waybillCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.waybill_status
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Short waybillStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.waybill_source
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String waybillSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.group_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.group_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.driver_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.driver_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String driverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.driver_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String driverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.vechicle_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long vechicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.vechicle_num
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String vechicleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.customer_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.customer_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.customer_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.sales_order
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String salesOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.cust_contact_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String custContactMan;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill_plan.send_wh_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long sendWhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill_plan.send_wh_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String sendWhName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.send_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String sendAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receiveMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receivePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receiveProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receiveCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receiveCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.receive_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String receiveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.transport_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Short transportWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.goods_type
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.start_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.arrive_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date arriveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.is_receipt
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Short isReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.is_urgent
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Short isUrgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.pickup_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String pickupWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.distribution_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String distributionWay;


    private String electronicalReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment1
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment1_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment2
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment2_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment3
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment3_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment4
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment4_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment5
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.attachment5_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String attachment5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.waybill_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String waybillRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.carrier_company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long carrierCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.carrier_company_id
     *
     * @mbg.generated Mon Feb 26 08:58:16 CST 2017
     */
    private String carrierCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.pub_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Date pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.finish_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Date finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.cancel_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Date cancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.cancel_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String cancelMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.cancel_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String cancelRemark;

    private Double longitude;

    private Double latitude;

    private String unloadLocation;

    private Date unloadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.create_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.create_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.create_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.update_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.update_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.update_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_waybill.is_deleted
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    private Short isDeleted;

    private String receivableName;

    private String payableName;



    /**
     * 重量
     */
    private Double weight;

    /**
     * 体积
     */
    private Double volume;

    /**
     * 运输距离
     */
    private Double distance;

    /**
     * 件数
     */
    private Double piece;

    /**
     * 商品重量单位
     */
    private String weightUnit;

    /**
     * 计价类型
     */
    private Byte pricingType;

    /**
     * 应收单价
     */
    private Float freightPrice;

    /**
     * 应收运费
     */
    private Float freightTotal;

    /**
     * 应付单价
     */
    private Float payPrice;

    /**
     * 应付总价
     */
    private Float payTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.id
     *
     * @return the value of t_waybill.id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.id
     *
     * @param id the value for t_waybill.id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_plan_id
     *
     * @return the value of t_waybill.waybill_plan_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getWaybillPlanId() {
        return waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.split_goods_id
     *
     * @param splitGoodsId the value for t_waybill.split_goods_id
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSplitGoodsId(Long splitGoodsId) {
        this.splitGoodsId = splitGoodsId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.split_goods_id
     *
     * @return the value of t_waybill.split_goods_id
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getSplitGoodsId() {
        return splitGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.waybill_plan_id
     *
     * @param waybillPlanId the value for t_waybill.waybill_plan_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setWaybillPlanId(Long waybillPlanId) {
        this.waybillPlanId = waybillPlanId;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_code
     *
     * @return the value of t_waybill.waybill_code
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getWaybillCode() {
        return waybillCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.waybill_code
     *
     * @param waybillCode the value for t_waybill.waybill_code
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setWaybillCode(String waybillCode) {
        this.waybillCode = waybillCode == null ? null : waybillCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_status
     *
     * @return the value of t_waybill.waybill_status
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Short getWaybillStatus() {
        return waybillStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.waybill_status
     *
     * @param waybillStatus the value for t_waybill.waybill_status
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setWaybillStatus(Short waybillStatus) {
        this.waybillStatus = waybillStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_source
     *
     * @return the value of t_waybill.waybill_source
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getWaybillSource() {
        return waybillSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_source
     *
     * @return the value of t_waybill.waybill_source
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setWaybillSource(String waybillSource) {
        this.waybillSource = waybillSource == null ? null : waybillSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.group_id
     *
     * @return the value of t_waybill.group_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.group_id
     *
     * @param groupId the value for t_waybill.group_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.group_name
     *
     * @return the value of t_waybill.group_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.group_name
     *
     * @param groupName the value for t_waybill.group_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.driver_id
     *
     * @return the value of t_waybill.driver_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.driver_id
     *
     * @param driverId the value for t_waybill.driver_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.driver_name
     *
     * @return the value of t_waybill.driver_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.driver_name
     *
     * @param driverName the value for t_waybill.driver_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName == null ? null : driverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.driver_phone
     *
     * @return the value of t_waybill.driver_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.driver_phone
     *
     * @param driverPhone the value for t_waybill.driver_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setDriverPhone(String driverPhone) {
        this.driverPhone = driverPhone == null ? null : driverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.vechicle_id
     *
     * @return the value of t_waybill.vechicle_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getVechicleId() {
        return vechicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.vechicle_id
     *
     * @param vechicleId the value for t_waybill.vechicle_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setVechicleId(Long vechicleId) {
        this.vechicleId = vechicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.vechicle_num
     *
     * @return the value of t_waybill.vechicle_num
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getVechicleNum() {
        return vechicleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.vechicle_num
     *
     * @param vechicleNum the value for t_waybill.vechicle_num
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setVechicleNum(String vechicleNum) {
        this.vechicleNum = vechicleNum == null ? null : vechicleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.customer_id
     *
     * @return the value of t_waybill.customer_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.customer_id
     *
     * @param customerId the value for t_waybill.customer_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.customer_name
     *
     * @return the value of t_waybill.customer_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.customer_name
     *
     * @param customerName the value for t_waybill.customer_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.customer_phone
     *
     * @return the value of t_waybill.customer_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.customer_phone
     *
     * @param customerPhone the value for t_waybill.customer_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.sales_order
     *
     * @return the value of t_waybill.sales_order
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSalesOrder() {
        return salesOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.sales_order
     *
     * @param salesOrder the value for t_waybill.sales_order
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSalesOrder(String salesOrder) {
        this.salesOrder = salesOrder == null ? null : salesOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.cust_contact_man
     *
     * @return the value of t_waybill.cust_contact_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCustContactMan() {
        return custContactMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.cust_contact_man
     *
     * @param custContactMan the value for t_waybill.cust_contact_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCustContactMan(String custContactMan) {
        this.custContactMan = custContactMan == null ? null : custContactMan.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill_plan.send_wh_id
     *
     * @return the value of t_waybill_plan.send_wh_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getSendWhId() {
        return sendWhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill_plan.send_wh_id
     *
     * @param sendWhId the value for t_waybill_plan.send_wh_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSendWhId(Long sendWhId) {
        this.sendWhId = sendWhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill_plan.send_wh_name
     *
     * @return the value of t_waybill_plan.send_wh_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getSendWhName() {
        return sendWhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill_plan.send_wh_name
     *
     * @param sendWhName the value for t_waybill_plan.send_wh_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setSendWhName(String sendWhName) {
        this.sendWhName = sendWhName == null ? null : sendWhName.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_man
     *
     * @return the value of t_waybill.send_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendMan() {
        return sendMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_man
     *
     * @param sendMan the value for t_waybill.send_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendMan(String sendMan) {
        this.sendMan = sendMan == null ? null : sendMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_phone
     *
     * @return the value of t_waybill.send_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendPhone() {
        return sendPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_phone
     *
     * @param sendPhone the value for t_waybill.send_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendPhone(String sendPhone) {
        this.sendPhone = sendPhone == null ? null : sendPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_province
     *
     * @return the value of t_waybill.send_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_province
     *
     * @param sendProvince the value for t_waybill.send_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_city
     *
     * @return the value of t_waybill.send_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_city
     *
     * @param sendCity the value for t_waybill.send_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_county
     *
     * @return the value of t_waybill.send_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendCounty() {
        return sendCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_county
     *
     * @param sendCounty the value for t_waybill.send_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendCounty(String sendCounty) {
        this.sendCounty = sendCounty == null ? null : sendCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.send_address
     *
     * @return the value of t_waybill.send_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.send_address
     *
     * @param sendAddress the value for t_waybill.send_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress == null ? null : sendAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_man
     *
     * @return the value of t_waybill.receive_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceiveMan() {
        return receiveMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_man
     *
     * @param receiveMan the value for t_waybill.receive_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceiveMan(String receiveMan) {
        this.receiveMan = receiveMan == null ? null : receiveMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_phone
     *
     * @return the value of t_waybill.receive_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_phone
     *
     * @param receivePhone the value for t_waybill.receive_phone
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone == null ? null : receivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_province
     *
     * @return the value of t_waybill.receive_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceiveProvince() {
        return receiveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_province
     *
     * @param receiveProvince the value for t_waybill.receive_province
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceiveProvince(String receiveProvince) {
        this.receiveProvince = receiveProvince == null ? null : receiveProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_city
     *
     * @return the value of t_waybill.receive_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceiveCity() {
        return receiveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_city
     *
     * @param receiveCity the value for t_waybill.receive_city
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceiveCity(String receiveCity) {
        this.receiveCity = receiveCity == null ? null : receiveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_county
     *
     * @return the value of t_waybill.receive_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceiveCounty() {
        return receiveCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_county
     *
     * @param receiveCounty the value for t_waybill.receive_county
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceiveCounty(String receiveCounty) {
        this.receiveCounty = receiveCounty == null ? null : receiveCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.receive_address
     *
     * @return the value of t_waybill.receive_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.receive_address
     *
     * @param receiveAddress the value for t_waybill.receive_address
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.transport_way
     *
     * @return the value of t_waybill.transport_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Short getTransportWay() {
        return transportWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.transport_way
     *
     * @param transportWay the value for t_waybill.transport_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setTransportWay(Short transportWay) {
        this.transportWay = transportWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.goods_type
     *
     * @return the value of t_waybill.goods_type
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.goods_type
     *
     * @param goodsType the value for t_waybill.goods_type
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.start_date
     *
     * @return the value of t_waybill.start_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.start_date
     *
     * @param startDate the value for t_waybill.start_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.arrive_date
     *
     * @return the value of t_waybill.arrive_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.arrive_date
     *
     * @param arriveDate the value for t_waybill.arrive_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.is_receipt
     *
     * @return the value of t_waybill.is_receipt
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Short getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.is_receipt
     *
     * @param isReceipt the value for t_waybill.is_receipt
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setIsReceipt(Short isReceipt) {
        this.isReceipt = isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.is_urgent
     *
     * @return the value of t_waybill.is_urgent
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Short getIsUrgent() {
        return isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.is_urgent
     *
     * @param isUrgent the value for t_waybill.is_urgent
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setIsUrgent(Short isUrgent) {
        this.isUrgent = isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.pickup_way
     *
     * @return the value of t_waybill.pickup_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getPickupWay() {
        return pickupWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.pickup_way
     *
     * @param pickupWay the value for t_waybill.pickup_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setPickupWay(String pickupWay) {
        this.pickupWay = pickupWay == null ? null : pickupWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.distribution_way
     *
     * @return the value of t_waybill.distribution_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getDistributionWay() {
        return distributionWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.distribution_way
     *
     * @param distributionWay the value for t_waybill.distribution_way
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setDistributionWay(String distributionWay) {
        this.distributionWay = distributionWay == null ? null : distributionWay.trim();
    }

    public String getElectronicalReceipt() {
        return electronicalReceipt==null?"[]":electronicalReceipt;
    }

    public void setElectronicalReceipt(String electronicalReceipt) {
        this.electronicalReceipt = electronicalReceipt==null?null:electronicalReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment1
     *
     * @return the value of t_waybill.attachment1
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment1() {
        return attachment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment1
     *
     * @param attachment1 the value for t_waybill.attachment1
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment1(String attachment1) {
        this.attachment1 = attachment1 == null ? null : attachment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment1_name
     *
     * @return the value of t_waybill.attachment1_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment1Name() {
        return attachment1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment1_name
     *
     * @param attachment1Name the value for t_waybill.attachment1_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment1Name(String attachment1Name) {
        this.attachment1Name = attachment1Name == null ? null : attachment1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment2
     *
     * @return the value of t_waybill.attachment2
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment2() {
        return attachment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment2
     *
     * @param attachment2 the value for t_waybill.attachment2
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment2(String attachment2) {
        this.attachment2 = attachment2 == null ? null : attachment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment2_name
     *
     * @return the value of t_waybill.attachment2_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment2Name() {
        return attachment2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment2_name
     *
     * @param attachment2Name the value for t_waybill.attachment2_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment2Name(String attachment2Name) {
        this.attachment2Name = attachment2Name == null ? null : attachment2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment3
     *
     * @return the value of t_waybill.attachment3
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment3() {
        return attachment3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment3
     *
     * @param attachment3 the value for t_waybill.attachment3
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment3(String attachment3) {
        this.attachment3 = attachment3 == null ? null : attachment3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment3_name
     *
     * @return the value of t_waybill.attachment3_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment3Name() {
        return attachment3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment3_name
     *
     * @param attachment3Name the value for t_waybill.attachment3_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment3Name(String attachment3Name) {
        this.attachment3Name = attachment3Name == null ? null : attachment3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment4
     *
     * @return the value of t_waybill.attachment4
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment4() {
        return attachment4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment4
     *
     * @param attachment4 the value for t_waybill.attachment4
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment4(String attachment4) {
        this.attachment4 = attachment4 == null ? null : attachment4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment4_name
     *
     * @return the value of t_waybill.attachment4_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment4Name() {
        return attachment4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment4_name
     *
     * @param attachment4Name the value for t_waybill.attachment4_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment4Name(String attachment4Name) {
        this.attachment4Name = attachment4Name == null ? null : attachment4Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment5
     *
     * @return the value of t_waybill.attachment5
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment5() {
        return attachment5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment5
     *
     * @param attachment5 the value for t_waybill.attachment5
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment5(String attachment5) {
        this.attachment5 = attachment5 == null ? null : attachment5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.attachment5_name
     *
     * @return the value of t_waybill.attachment5_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getAttachment5Name() {
        return attachment5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.attachment5_name
     *
     * @param attachment5Name the value for t_waybill.attachment5_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setAttachment5Name(String attachment5Name) {
        this.attachment5Name = attachment5Name == null ? null : attachment5Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.waybill_remark
     *
     * @return the value of t_waybill.waybill_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getWaybillRemark() {
        return waybillRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.waybill_remark
     *
     * @param waybillRemark the value for t_waybill.waybill_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setWaybillRemark(String waybillRemark) {
        this.waybillRemark = waybillRemark == null ? null : waybillRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.carrier_company_id
     *
     * @return the value of t_waybill.carrier_company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getCarrierCompanyId() {
        return carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.carrier_company_id
     *
     * @param carrierCompanyId the value for t_waybill.carrier_company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCarrierCompanyId(Long carrierCompanyId) {
        this.carrierCompanyId = carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.carrier_company_name
     *
     * @return the value of t_waybill.carrier_company_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCarrierCompanyName() {
        return carrierCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.carrier_company_name
     *
     * @param carrierCompanyName the value for t_waybill.carrier_company_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCarrierCompanyName(String carrierCompanyName) {
        this.carrierCompanyName = carrierCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.company_id
     *
     * @return the value of t_waybill.company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.company_id
     *
     * @param companyId the value for t_waybill.company_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.pub_date
     *
     * @return the value of t_waybill.pub_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.pub_date
     *
     * @param pubDate the value for t_waybill.pub_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.finish_date
     *
     * @return the value of t_waybill.finish_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.finish_date
     *
     * @param finishDate the value for t_waybill.finish_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.cancel_date
     *
     * @return the value of t_waybill.cancel_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.cancel_date
     *
     * @param cancelDate the value for t_waybill.cancel_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.cancel_man
     *
     * @return the value of t_waybill.cancel_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCancelMan() {
        return cancelMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.cancel_man
     *
     * @param cancelMan the value for t_waybill.cancel_man
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCancelMan(String cancelMan) {
        this.cancelMan = cancelMan == null ? null : cancelMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.cancel_remark
     *
     * @return the value of t_waybill.cancel_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCancelRemark() {
        return cancelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.cancel_remark
     *
     * @param cancelRemark the value for t_waybill.cancel_remark
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCancelRemark(String cancelRemark) {
        this.cancelRemark = cancelRemark == null ? null : cancelRemark.trim();
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public String getUnloadLocation() {
        return unloadLocation;
    }

    public void setUnloadLocation(String unloadLocation) {
        this.unloadLocation = unloadLocation;
    }

    public Date getUnloadTime() {
        return unloadTime;
    }

    public void setUnloadTime(Date unloadTime) {
        this.unloadTime = unloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.create_id
     *
     * @return the value of t_waybill.create_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.create_id
     *
     * @param createId the value for t_waybill.create_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.create_name
     *
     * @return the value of t_waybill.create_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.create_name
     *
     * @param createName the value for t_waybill.create_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.create_date
     *
     * @return the value of t_waybill.create_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.create_date
     *
     * @param createDate the value for t_waybill.create_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.update_id
     *
     * @return the value of t_waybill.update_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.update_id
     *
     * @param updateId the value for t_waybill.update_id
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.update_name
     *
     * @return the value of t_waybill.update_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.update_name
     *
     * @param updateName the value for t_waybill.update_name
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.update_date
     *
     * @return the value of t_waybill.update_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.update_date
     *
     * @param updateDate the value for t_waybill.update_date
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_waybill.is_deleted
     *
     * @return the value of t_waybill.is_deleted
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_waybill.is_delete
     *
     * @param isDeleted the value for t_waybill.is_deleted
     *
     * @mbg.generated Wed Dec 20 10:13:16 CST 2017
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getReceivableName() {
        return receivableName;
    }

    public void setReceivableName(String receivableName) {
        this.receivableName = receivableName;
    }

    public String getPayableName() {
        return payableName;
    }

    public void setPayableName(String payableName) {
        this.payableName = payableName;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    public Double getVolume() {
        return volume;
    }

    public void setVolume(Double volume) {
        this.volume = volume;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public Double getPiece() {
        return piece;
    }

    public void setPiece(Double piece) {
        this.piece = piece;
    }

    public String getWeightUnit() {
        return weightUnit;
    }

    public void setWeightUnit(String weightUnit) {
        this.weightUnit = weightUnit;
    }

    public Byte getPricingType() {
        return pricingType;
    }

    public void setPricingType(Byte pricingType) {
        this.pricingType = pricingType;
    }

    public Float getFreightPrice() {
        return freightPrice;
    }

    public void setFreightPrice(Float freightPrice) {
        this.freightPrice = freightPrice;
    }

    public Float getFreightTotal() {
        return freightTotal;
    }

    public void setFreightTotal(Float freightTotal) {
        this.freightTotal = freightTotal;
    }

    public Float getPayPrice() {
        return payPrice;
    }

    public void setPayPrice(Float payPrice) {
        this.payPrice = payPrice;
    }

    public Float getPayTotal() {
        return payTotal;
    }

    public void setPayTotal(Float payTotal) {
        this.payTotal = payTotal;
    }
}