package com.lcdt.cwms.user.model;

import java.util.Date;

public class WmsCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.comp_id
     *
     * @mbg.generated
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.auth_status
     *
     * @mbg.generated
     */
    private Short authStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.short_name
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.contact_way
     *
     * @mbg.generated
     */
    private String contactWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.region_info
     *
     * @mbg.generated
     */
    private String regionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.reg_address
     *
     * @mbg.generated
     */
    private String regAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.create_dt
     *
     * @mbg.generated
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.reg_capital
     *
     * @mbg.generated
     */
    private String regCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.business_scope
     *
     * @mbg.generated
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.comp_intro
     *
     * @mbg.generated
     */
    private String compIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.reg_dt
     *
     * @mbg.generated
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_company.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.comp_id
     *
     * @return the value of t_ue_company.comp_id
     *
     * @mbg.generated
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.comp_id
     *
     * @param compId the value for t_ue_company.comp_id
     *
     * @mbg.generated
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.full_name
     *
     * @return the value of t_ue_company.full_name
     *
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.full_name
     *
     * @param fullName the value for t_ue_company.full_name
     *
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.auth_status
     *
     * @return the value of t_ue_company.auth_status
     *
     * @mbg.generated
     */
    public Short getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.auth_status
     *
     * @param authStatus the value for t_ue_company.auth_status
     *
     * @mbg.generated
     */
    public void setAuthStatus(Short authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.short_name
     *
     * @return the value of t_ue_company.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.short_name
     *
     * @param shortName the value for t_ue_company.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.admin_name
     *
     * @return the value of t_ue_company.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.admin_name
     *
     * @param adminName the value for t_ue_company.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.contact_way
     *
     * @return the value of t_ue_company.contact_way
     *
     * @mbg.generated
     */
    public String getContactWay() {
        return contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.contact_way
     *
     * @param contactWay the value for t_ue_company.contact_way
     *
     * @mbg.generated
     */
    public void setContactWay(String contactWay) {
        this.contactWay = contactWay == null ? null : contactWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.region_info
     *
     * @return the value of t_ue_company.region_info
     *
     * @mbg.generated
     */
    public String getRegionInfo() {
        return regionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.region_info
     *
     * @param regionInfo the value for t_ue_company.region_info
     *
     * @mbg.generated
     */
    public void setRegionInfo(String regionInfo) {
        this.regionInfo = regionInfo == null ? null : regionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.reg_address
     *
     * @return the value of t_ue_company.reg_address
     *
     * @mbg.generated
     */
    public String getRegAddress() {
        return regAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.reg_address
     *
     * @param regAddress the value for t_ue_company.reg_address
     *
     * @mbg.generated
     */
    public void setRegAddress(String regAddress) {
        this.regAddress = regAddress == null ? null : regAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.create_dt
     *
     * @return the value of t_ue_company.create_dt
     *
     * @mbg.generated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.create_dt
     *
     * @param createDt the value for t_ue_company.create_dt
     *
     * @mbg.generated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.reg_capital
     *
     * @return the value of t_ue_company.reg_capital
     *
     * @mbg.generated
     */
    public String getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.reg_capital
     *
     * @param regCapital the value for t_ue_company.reg_capital
     *
     * @mbg.generated
     */
    public void setRegCapital(String regCapital) {
        this.regCapital = regCapital == null ? null : regCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.business_scope
     *
     * @return the value of t_ue_company.business_scope
     *
     * @mbg.generated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.business_scope
     *
     * @param businessScope the value for t_ue_company.business_scope
     *
     * @mbg.generated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.comp_intro
     *
     * @return the value of t_ue_company.comp_intro
     *
     * @mbg.generated
     */
    public String getCompIntro() {
        return compIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.comp_intro
     *
     * @param compIntro the value for t_ue_company.comp_intro
     *
     * @mbg.generated
     */
    public void setCompIntro(String compIntro) {
        this.compIntro = compIntro == null ? null : compIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.reg_dt
     *
     * @return the value of t_ue_company.reg_dt
     *
     * @mbg.generated
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.reg_dt
     *
     * @param regDt the value for t_ue_company.reg_dt
     *
     * @mbg.generated
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.remark
     *
     * @return the value of t_ue_company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.remark
     *
     * @param remark the value for t_ue_company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.industry
     *
     * @return the value of t_ue_company.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.industry
     *
     * @param industry the value for t_ue_company.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_company.create_user_id
     *
     * @return the value of t_ue_company.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_company.create_user_id
     *
     * @param createUserId the value for t_ue_company.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }
}