package com.lcdt.cwms.user.model;

import java.util.Date;

public class WmsCompanyUserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_group.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ue_group.create_dt
     *
     * @mbg.generated
     */
    private Date createDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_group.group_id
     *
     * @return the value of t_ue_group.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_group.group_id
     *
     * @param groupId the value for t_ue_group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_group.company_id
     *
     * @return the value of t_ue_group.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_group.company_id
     *
     * @param companyId the value for t_ue_group.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_group.group_name
     *
     * @return the value of t_ue_group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_group.group_name
     *
     * @param groupName the value for t_ue_group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ue_group.create_dt
     *
     * @return the value of t_ue_group.create_dt
     *
     * @mbg.generated
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ue_group.create_dt
     *
     * @param createDt the value for t_ue_group.create_dt
     *
     * @mbg.generated
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }
}