package com.lcdt.client.model;

import java.util.List;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_id
     *
     * @mbg.generated
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.short_name
     *
     * @mbg.generated
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_code
     *
     * @mbg.generated
     */
    private String clientCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.client_type
     *
     * @mbg.generated
     */
    private Short clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.group_ids
     *
     * @mbg.generated
     */
    private String groupIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.group_names
     *
     * @mbg.generated
     */
    private String groupNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.tel_no
     *
     * @mbg.generated
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.attachment_1
     *
     * @mbg.generated
     */
    private String attachment1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.attachment_2
     *
     * @mbg.generated
     */
    private String attachment2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.invoice_title
     *
     * @mbg.generated
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.registration_no
     *
     * @mbg.generated
     */
    private String registrationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.bank_no
     *
     * @mbg.generated
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.registration_address
     *
     * @mbg.generated
     */
    private String registrationAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.tel_no1
     *
     * @mbg.generated
     */
    private String telNo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.invoice_remark
     *
     * @mbg.generated
     */
    private String invoiceRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.bind_cpid
     *
     * @mbg.generated
     */
    private Long bindCpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.bind_company
     *
     * @mbg.generated
     */
    private String bindCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client.status
     *
     * @mbg.generated
     */
    private Short status;


    private List<ClientLinkman> clientLinkmanList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_id
     *
     * @return the value of t_client.client_id
     *
     * @mbg.generated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_id
     *
     * @param clientId the value for t_client.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_name
     *
     * @return the value of t_client.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_name
     *
     * @param clientName the value for t_client.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.short_name
     *
     * @return the value of t_client.short_name
     *
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.short_name
     *
     * @param shortName the value for t_client.short_name
     *
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_code
     *
     * @return the value of t_client.client_code
     *
     * @mbg.generated
     */
    public String getClientCode() {
        return clientCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_code
     *
     * @param clientCode the value for t_client.client_code
     *
     * @mbg.generated
     */
    public void setClientCode(String clientCode) {
        this.clientCode = clientCode == null ? null : clientCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.client_type
     *
     * @return the value of t_client.client_type
     *
     * @mbg.generated
     */
    public Short getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.client_type
     *
     * @param clientType the value for t_client.client_type
     *
     * @mbg.generated
     */
    public void setClientType(Short clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.province
     *
     * @return the value of t_client.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.province
     *
     * @param province the value for t_client.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.city
     *
     * @return the value of t_client.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.city
     *
     * @param city the value for t_client.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.county
     *
     * @return the value of t_client.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.county
     *
     * @param county the value for t_client.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.detail_address
     *
     * @return the value of t_client.detail_address
     *
     * @mbg.generated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.detail_address
     *
     * @param detailAddress the value for t_client.detail_address
     *
     * @mbg.generated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.group_ids
     *
     * @return the value of t_client.group_ids
     *
     * @mbg.generated
     */
    public String getGroupIds() {
        return groupIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.group_ids
     *
     * @param groupIds the value for t_client.group_ids
     *
     * @mbg.generated
     */
    public void setGroupIds(String groupIds) {
        this.groupIds = groupIds == null ? null : groupIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.group_names
     *
     * @return the value of t_client.group_names
     *
     * @mbg.generated
     */
    public String getGroupNames() {
        return groupNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.group_names
     *
     * @param groupNames the value for t_client.group_names
     *
     * @mbg.generated
     */
    public void setGroupNames(String groupNames) {
        this.groupNames = groupNames == null ? null : groupNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.post_code
     *
     * @return the value of t_client.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.post_code
     *
     * @param postCode the value for t_client.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.tel_no
     *
     * @return the value of t_client.tel_no
     *
     * @mbg.generated
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.tel_no
     *
     * @param telNo the value for t_client.tel_no
     *
     * @mbg.generated
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.fax
     *
     * @return the value of t_client.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.fax
     *
     * @param fax the value for t_client.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.remark
     *
     * @return the value of t_client.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.remark
     *
     * @param remark the value for t_client.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.attachment_1
     *
     * @return the value of t_client.attachment_1
     *
     * @mbg.generated
     */
    public String getAttachment1() {
        return attachment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.attachment_1
     *
     * @param attachment1 the value for t_client.attachment_1
     *
     * @mbg.generated
     */
    public void setAttachment1(String attachment1) {
        this.attachment1 = attachment1 == null ? null : attachment1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.attachment_2
     *
     * @return the value of t_client.attachment_2
     *
     * @mbg.generated
     */
    public String getAttachment2() {
        return attachment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.attachment_2
     *
     * @param attachment2 the value for t_client.attachment_2
     *
     * @mbg.generated
     */
    public void setAttachment2(String attachment2) {
        this.attachment2 = attachment2 == null ? null : attachment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.invoice_title
     *
     * @return the value of t_client.invoice_title
     *
     * @mbg.generated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.invoice_title
     *
     * @param invoiceTitle the value for t_client.invoice_title
     *
     * @mbg.generated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.registration_no
     *
     * @return the value of t_client.registration_no
     *
     * @mbg.generated
     */
    public String getRegistrationNo() {
        return registrationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.registration_no
     *
     * @param registrationNo the value for t_client.registration_no
     *
     * @mbg.generated
     */
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo == null ? null : registrationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.bank_name
     *
     * @return the value of t_client.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.bank_name
     *
     * @param bankName the value for t_client.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.bank_no
     *
     * @return the value of t_client.bank_no
     *
     * @mbg.generated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.bank_no
     *
     * @param bankNo the value for t_client.bank_no
     *
     * @mbg.generated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.registration_address
     *
     * @return the value of t_client.registration_address
     *
     * @mbg.generated
     */
    public String getRegistrationAddress() {
        return registrationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.registration_address
     *
     * @param registrationAddress the value for t_client.registration_address
     *
     * @mbg.generated
     */
    public void setRegistrationAddress(String registrationAddress) {
        this.registrationAddress = registrationAddress == null ? null : registrationAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.tel_no1
     *
     * @return the value of t_client.tel_no1
     *
     * @mbg.generated
     */
    public String getTelNo1() {
        return telNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.tel_no1
     *
     * @param telNo1 the value for t_client.tel_no1
     *
     * @mbg.generated
     */
    public void setTelNo1(String telNo1) {
        this.telNo1 = telNo1 == null ? null : telNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.invoice_remark
     *
     * @return the value of t_client.invoice_remark
     *
     * @mbg.generated
     */
    public String getInvoiceRemark() {
        return invoiceRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.invoice_remark
     *
     * @param invoiceRemark the value for t_client.invoice_remark
     *
     * @mbg.generated
     */
    public void setInvoiceRemark(String invoiceRemark) {
        this.invoiceRemark = invoiceRemark == null ? null : invoiceRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.company_id
     *
     * @return the value of t_client.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.company_id
     *
     * @param companyId the value for t_client.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.bind_cpid
     *
     * @return the value of t_client.bind_cpid
     *
     * @mbg.generated
     */
    public Long getBindCpid() {
        return bindCpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.bind_cpid
     *
     * @param bindCpid the value for t_client.bind_cpid
     *
     * @mbg.generated
     */
    public void setBindCpid(Long bindCpid) {
        this.bindCpid = bindCpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.bind_company
     *
     * @return the value of t_client.bind_company
     *
     * @mbg.generated
     */
    public String getBindCompany() {
        return bindCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.bind_company
     *
     * @param bindCompany the value for t_client.bind_company
     *
     * @mbg.generated
     */
    public void setBindCompany(String bindCompany) {
        this.bindCompany = bindCompany == null ? null : bindCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client.status
     *
     * @return the value of t_client.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client.status
     *
     * @param status the value for t_client.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    public List<ClientLinkman> getClientLinkmanList() {
        return clientLinkmanList;
    }

    public void setClientLinkmanList(List<ClientLinkman> clientLinkmanList) {
        this.clientLinkmanList = clientLinkmanList;
    }
}

