package com.lcdt.client.model;

import java.util.Date;

public class MyLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.my_linkman_id
     *
     * @mbg.generated
     */
    private Long myLinkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.my_client_ids
     *
     * @mbg.generated
     */
    private String myClientIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.my_client_names
     *
     * @mbg.generated
     */
    private String myClientNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.my_linkman_id
     *
     * @return the value of t_my_linkman.my_linkman_id
     *
     * @mbg.generated
     */
    public Long getMyLinkmanId() {
        return myLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.my_linkman_id
     *
     * @param myLinkmanId the value for t_my_linkman.my_linkman_id
     *
     * @mbg.generated
     */
    public void setMyLinkmanId(Long myLinkmanId) {
        this.myLinkmanId = myLinkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.name
     *
     * @return the value of t_my_linkman.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.name
     *
     * @param name the value for t_my_linkman.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.my_client_ids
     *
     * @return the value of t_my_linkman.my_client_ids
     *
     * @mbg.generated
     */
    public String getMyClientIds() {
        return myClientIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.my_client_ids
     *
     * @param myClientIds the value for t_my_linkman.my_client_ids
     *
     * @mbg.generated
     */
    public void setMyClientIds(String myClientIds) {
        this.myClientIds = myClientIds == null ? null : myClientIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.my_client_names
     *
     * @return the value of t_my_linkman.my_client_names
     *
     * @mbg.generated
     */
    public String getMyClientNames() {
        return myClientNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.my_client_names
     *
     * @param myClientNames the value for t_my_linkman.my_client_names
     *
     * @mbg.generated
     */
    public void setMyClientNames(String myClientNames) {
        this.myClientNames = myClientNames == null ? null : myClientNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.duty
     *
     * @return the value of t_my_linkman.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.duty
     *
     * @param duty the value for t_my_linkman.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.mobile
     *
     * @return the value of t_my_linkman.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.mobile
     *
     * @param mobile the value for t_my_linkman.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.mail
     *
     * @return the value of t_my_linkman.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.mail
     *
     * @param mail the value for t_my_linkman.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.birthday
     *
     * @return the value of t_my_linkman.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.birthday
     *
     * @param birthday the value for t_my_linkman.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.sex
     *
     * @return the value of t_my_linkman.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.sex
     *
     * @param sex the value for t_my_linkman.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.province
     *
     * @return the value of t_my_linkman.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.province
     *
     * @param province the value for t_my_linkman.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.city
     *
     * @return the value of t_my_linkman.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.city
     *
     * @param city the value for t_my_linkman.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.county
     *
     * @return the value of t_my_linkman.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.county
     *
     * @param county the value for t_my_linkman.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.detail_address
     *
     * @return the value of t_my_linkman.detail_address
     *
     * @mbg.generated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.detail_address
     *
     * @param detailAddress the value for t_my_linkman.detail_address
     *
     * @mbg.generated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.remark
     *
     * @return the value of t_my_linkman.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.remark
     *
     * @param remark the value for t_my_linkman.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_linkman.company_id
     *
     * @return the value of t_my_linkman.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_linkman.company_id
     *
     * @param companyId the value for t_my_linkman.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
}