package com.lcdt.client.model;

import java.util.Date;

public class MyLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.my_linkman_id
     *
     * @mbg.generated
     */
    private Long myLinkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.name
     *
     * @mbg.generated
     */
    private String name;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.detail_address
     *
     * @mbg.generated
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_linkman.company_id
     *
     * @mbg.generated
     */
    private Long companyId;


}