package com.lcdt.traffic.model;

import com.lcdt.converter.ResponseData;

import java.util.Date;

public class PlanLeaveMsg implements java.io.Serializable,ResponseData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.plan_leave_msg_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long planLeaveMsgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long waybillPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.leave_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short leaveType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.leave_msg
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String leaveMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.leave_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date leaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.shipper_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String shipperName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long carrierCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.carrier_company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.carrier_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String carrierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_leave_msg.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    private Short isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.plan_leave_msg_id
     *
     * @return the value of t_plan_leave_msg.plan_leave_msg_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getPlanLeaveMsgId() {
        return planLeaveMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.plan_leave_msg_id
     *
     * @param planLeaveMsgId the value for t_plan_leave_msg.plan_leave_msg_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setPlanLeaveMsgId(Long planLeaveMsgId) {
        this.planLeaveMsgId = planLeaveMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.waybill_plan_id
     *
     * @return the value of t_plan_leave_msg.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getWaybillPlanId() {
        return waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.waybill_plan_id
     *
     * @param waybillPlanId the value for t_plan_leave_msg.waybill_plan_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setWaybillPlanId(Long waybillPlanId) {
        this.waybillPlanId = waybillPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.leave_type
     *
     * @return the value of t_plan_leave_msg.leave_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.leave_type
     *
     * @param leaveType the value for t_plan_leave_msg.leave_type
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setLeaveType(Short leaveType) {
        this.leaveType = leaveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.leave_msg
     *
     * @return the value of t_plan_leave_msg.leave_msg
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getLeaveMsg() {
        return leaveMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.leave_msg
     *
     * @param leaveMsg the value for t_plan_leave_msg.leave_msg
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setLeaveMsg(String leaveMsg) {
        this.leaveMsg = leaveMsg == null ? null : leaveMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.leave_date
     *
     * @return the value of t_plan_leave_msg.leave_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.leave_date
     *
     * @param leaveDate the value for t_plan_leave_msg.leave_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.company_id
     *
     * @return the value of t_plan_leave_msg.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.company_id
     *
     * @param companyId the value for t_plan_leave_msg.company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.company_name
     *
     * @return the value of t_plan_leave_msg.company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.company_name
     *
     * @param companyName the value for t_plan_leave_msg.company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.shipper_name
     *
     * @return the value of t_plan_leave_msg.shipper_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.shipper_name
     *
     * @param shipperName the value for t_plan_leave_msg.shipper_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setShipperName(String shipperName) {
        this.shipperName = shipperName == null ? null : shipperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.carrier_company_id
     *
     * @return the value of t_plan_leave_msg.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCarrierCompanyId() {
        return carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.carrier_company_id
     *
     * @param carrierCompanyId the value for t_plan_leave_msg.carrier_company_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierCompanyId(Long carrierCompanyId) {
        this.carrierCompanyId = carrierCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.carrier_company_name
     *
     * @return the value of t_plan_leave_msg.carrier_company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierCompanyName() {
        return carrierCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.carrier_company_name
     *
     * @param carrierCompanyName the value for t_plan_leave_msg.carrier_company_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierCompanyName(String carrierCompanyName) {
        this.carrierCompanyName = carrierCompanyName == null ? null : carrierCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.carrier_name
     *
     * @return the value of t_plan_leave_msg.carrier_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.carrier_name
     *
     * @param carrierName the value for t_plan_leave_msg.carrier_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName == null ? null : carrierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.create_id
     *
     * @return the value of t_plan_leave_msg.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.create_id
     *
     * @param createId the value for t_plan_leave_msg.create_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.create_name
     *
     * @return the value of t_plan_leave_msg.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.create_name
     *
     * @param createName the value for t_plan_leave_msg.create_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.create_date
     *
     * @return the value of t_plan_leave_msg.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.create_date
     *
     * @param createDate the value for t_plan_leave_msg.create_date
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.update_id
     *
     * @return the value of t_plan_leave_msg.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.update_id
     *
     * @param updateId the value for t_plan_leave_msg.update_id
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.update_name
     *
     * @return the value of t_plan_leave_msg.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.update_name
     *
     * @param updateName the value for t_plan_leave_msg.update_name
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.update_time
     *
     * @return the value of t_plan_leave_msg.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.update_time
     *
     * @param updateTime the value for t_plan_leave_msg.update_time
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_leave_msg.is_deleted
     *
     * @return the value of t_plan_leave_msg.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_leave_msg.is_deleted
     *
     * @param isDeleted the value for t_plan_leave_msg.is_deleted
     *
     * @mbg.generated Tue Dec 12 09:56:12 CST 2017
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }
}